# Generated by Django 5.1.5 on 2025-01-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizzes',
            table='quizzes',
        ),
    ]
