# Generated by Django 5.1.5 on 2025-01-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_pdfdocument_course_pdfdocument_extracted_text'),
        ('quizzes', '0002_alter_quizzes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.pdfdocument'),
        ),
    ]
