# Generated by Django 5.1.5 on 2025-01-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
