# Generated by Django 5.1.5 on 2025-01-28 17:06

import adaptive_learning.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(storage=adaptive_learning.storages.PDFStorage(), upload_to=''),
        ),
    ]
