# Generated by Django 5.1.5 on 2025-01-28 17:27

import adaptive_learning.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_pdfdocument_file_url_alter_pdfdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(storage=adaptive_learning.storages.PDFStorage(), upload_to='pdfs/'),
        ),
    ]
