# Generated by Django 5.1.5 on 2025-01-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_pdfdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
