# Generated by Django 5.1.5 on 2025-01-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_pdfdocument_file_url'),
        ('courses', '0003_alter_courses_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
