# Generated by Django 5.1.5 on 2025-01-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
    ]
