# Generated by Django 5.1.5 on 2025-01-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
